DROP USER IF EXISTS 'app'@'%';
CREATE USER 'app'@'%' IDENTIFIED WITH mysql_native_password BY 'app';
GRANT ALL PRIVILEGES ON code_test_taskboard.* TO 'app'@'%';
FLUSH PRIVILEGES;

CREATE TABLE lists (
	uuid CHAR(36) NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description TEXT,
	sort_order INT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE tasks (
	uuid CHAR(36) NOT NULL PRIMARY KEY,
	list_uuid CHAR(36),
	title VARCHAR(100) NOT NULL,
	description TEXT,
	sort_order INT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;