CREATE TABLE lists (
	uuid CHAR(36) NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	description TEXT,
	sort_order INT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;