FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package and download dependencies
COPY package*.json ./
RUN npm install

# Copy code
COPY . .

# Expose port
EXPOSE 4200

# Run dev server
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll=2000"]