FROM golang:1.25-alpine

# Set working directory
WORKDIR /app

# Copy Go mod and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy code
COPY . .

# Build
RUN go build -o server .

# Expose port
EXPOSE 8080

# Run server
CMD ["./server"]
